services:
  ros_rpi:
    image: ilya9kkk/ros_arm:gpio
    container_name: ros_rpi
    platform: linux/arm64
    privileged: true
    stdin_open: true         # Открывает stdin
    tty: true                # Включает псевдотерминал
    network_mode: "host"
    ipc: "host"
    deploy:
      resources:
        limits:
          memory: 4g
    shm_size: '4g'
    devices:
      - "/dev:/dev"
      - "/dev/gpiomem:/dev/gpiomem"
    group_add:
      - 44
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY
      - LD_LIBRARY_PATH=/opt/vc/lib
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
      - ROS_MASTER_URI=http://localhost:11311  
      - ROS_HOSTNAME=192.168.0.108.local
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /opt/vc:/opt/vc
      - /dev:/dev
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - /home/rpi/rosrpi/workspace:/workspace
    entrypoint: ["/bin/bash", "-c", "/workspace/CONTAINER_START.bash"]

